#!/usr/bin/env bash

set -e

HOST=$1

sync-github-keys() {
	local CONTROL_KEY GITHUB_USERNAME
	CONTROL_KEY=`mktemp`
	GITHUB_USERNAME=$1
	# This priv key is intended to be public; we base64 encode it only so that it doesn't get automatically detected
	# by whitehat bots that send warnings
	echo "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAQEAtx/91VFc3BoLBKjHSUtFcg8tCpMM+c8sec8SmE5ZEllwyMceZcrV
INC5x9Iz+TISNKfretXFB9H+3VE27FqQlWwIs9SEl2GzA+7/gQhMCrKQY3bY0WfBxyFe4T
AoUqrZu463nJZpYgIFD2mlzae5b59cMCoyjleZLs075Dn6i+jykZlpPQHIzt6GluGowEDj
p2IjbKvItCiZ1WJNR2YZoMl7i/dZ2Qi2XDSLfEd7TlpNpgbk5JbyDKhRnwX+rpAp7RBlNp
WWzRGV1DUUiFRzZ1WysoSuHwytsyxKBy4NxW5tK5xSwbt+vpGQplv+MqUeOlNMTg/ErHcc
wPJc7rvRGwAAA9iaM97lmjPe5QAAAAdzc2gtcnNhAAABAQC3H/3VUVzcGgsEqMdJS0VyDy
0Kkwz5zyx5zxKYTlkSWXDIxx5lytUg0LnH0jP5MhI0p+t61cUH0f7dUTbsWpCVbAiz1ISX
YbMD7v+BCEwKspBjdtjRZ8HHIV7hMChSqtm7jreclmliAgUPaaXNp7lvn1wwKjKOV5kuzT
vkOfqL6PKRmWk9AcjO3oaW4ajAQOOnYiNsq8i0KJnVYk1HZhmgyXuL91nZCLZcNIt8R3tO
Wk2mBuTklvIMqFGfBf6ukCntEGU2lZbNEZXUNRSIVHNnVbKyhK4fDK2zLEoHLg3Fbm0rnF
LBu36+kZCmW/4ypR46U0xOD8SsdxzA8lzuu9EbAAAAAwEAAQAAAQBnp4weevd8/qDN+lsT
ea/NaBmuqp3lqQcby8JSw8ZXRJk6jLsAE1egQ4VlPe59V4JGm+YGmYn1a0BANgBIuNquOY
CTie+jYIHb8CRf/TpNs9VW96ayoXBmLtVt0byBToQATkBQOjNcbpg+qSZYyl+Ed0fPW5NS
TvM+Mp18CfVvy24K1FxGfcWhYlfm76sBFOakfjiY6HevXgRV++QAFANRsYGKaPYuTSZLxH
NZOale5Ca6axw05L+cvfEG56Ufoa5+Xz5oB6hrIYy7RzTrl7Gfpx+ouk1t6uxMMkKGg7Yt
7z+Koe+Jn1fsGdzbTyTTfwgMZtiakUsbCpEbKBTPknSBAAAAgFw7yomSKmKaI+OnXUAW2s
Y1n5WsrzQcV6uKJRs4zgbunkYRWFOByV56C7oqSMEywoLdpHChzOTVQ4i+Bp26/+9ZgM22
0ddRHqJFCbz1ktJY5RrmjyEXw1oewM7FH4HC1dKvLJ1GxG/vy5JhSa/EUQkSkydCSmTe1i
mFV15JDUDdAAAAgQDoOLOQhYZs+haWT9mbnhA6M1cvqi22rm464HE/pMAtZF1Ngzi/M2iU
R/Rq7Ieoea6ZIqC66tMVgQERz3AHOOMgG0wPQpdpVMAy8ZSBW2RtRJ5L3PqIDNs8NsVoPe
i27c7eMcf8lbR9Q73aRCuSP70RKlHYbkBzabnL/YaH8JzkaQAAAIEAyeBOhv0yEbFISd8T
2jn8RXY3sNqAKgn+sWj8zISBIXjz2+mlJim3LaqeUX3wDrpMYI02o6d/l9s5nxEO2DeFFK
PLUG/yzTkXTuv8RjI0qrcqdcvrfkrHba7C+lk1512hkDuSdVcKzfJlPAG2hW/Q1tMQROHl
B7+xB9lixzFqCOMAAAAeY29udHJvbEBzdHJlbWlvLWFkZG9uLWRlcGxveWVyAQIDBAU=" | base64 -d > $CONTROL_KEY
	chmod 0700 $CONTROL_KEY
	ssh -q -i $CONTROL_KEY dokku@"$HOST" sync-github-keys "$GITHUB_USERNAME"
	rm $CONTROL_KEY
}

if [ -z $HOST ]
then
	echo "Usage: beamup <host> <command>"
	exit 1
fi

if [ "$2" = "sync-github-keys" ]
then
	if [ -z $3 ]; then
		echo "Usage: beamup <host> sync-github-keys <github username>"
		exit 1
	fi
	sync-github-keys $3
	exit 0
fi

if [ "$2" = "add-remote" ]
then
	GITHUB_USERNAME=`echo $3 | awk '{print tolower($0)}'`
	if [ -z $3 ] || [ -z $4 ]; then
		echo "Usage: beamup <host> add-remote <github username> <app name>"
		exit 1
	fi
	GITHUB_USERNAME_HASHED=$( echo $GITHUB_USERNAME | shasum -a 256 | cut -c1-12 )
	# TODO automatic repo name
	git remote add beamup dokku@$HOST:$GITHUB_USERNAME_HASHED/$4 && echo Successfully added remote beamup
	sync-github-keys $GITHUB_USERNAME
	exit 0
fi

echo "Usage: beamup <host> <command>"
echo "unsupported command; supported: sync-github-keys, add-remote"
exit 1

