#!/usr/bin/env bash

set -e


HOST=$1

if [ "$2" = "sync-github-keys" ]
then
	CONTROL_KEY=`mktemp`
	# This priv key is intended to be public; we base64 encode it only so that it doesn't get automatically detected
	# by whitehat bots that send warnings
	echo "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhP
UUFBQUNDN2pnUFV6bmppOGp5WUFOWGtQOU16S3FrSE04OXNvanA2c296aEkybDVKd0FBQUppbkpk
MXNweVhkCmJBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQzdqZ1BVem5qaThqeVlBTlhrUDlNektx
a0hNODlzb2pwNnNvemhJMmw1SncKQUFBRUF6T3FGVDI1dEl0UmhCcGhobUpCY3p1c2xDVDhTYXpk
Ymd1NXZzbXUyM1VydU9BOVRPZU9MeVBKZ0ExZVEvMHpNcQpxUWN6ejJ5aU9ucXlqT0VqYVhrbkFB
QUFFR2wyYjBCcGRtOHRkR2hwYm10d1lXUUJBZ01FQlE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZB
VEUgS0VZLS0tLS0K" | base64 -d > $CONTROL_KEY
	chmod 0700 $CONTROL_KEY
	ssh -q -i $CONTROL_KEY dokku@"$HOST" sync-github-keys "$3"

	rm $CONTROL_KEY
	exit 0
fi

echo "unsupported command"
exit 1

