#!/usr/bin/env bash


# Or actually, alternatively we can do
# docker service create --name beamup_control_registry --mount type=volume,source=/var/lib/registry,destination=/var/lib/registry --publish published=5000,target=5000 registry:2

mkdir -p /var/lib/registry
cat <<EOF >registry.yaml
version: '3.7'
services:
   registry:
        image: registry:2
        volumes:
          - /var/lib/registry:/var/lib/registry
        ports:
          - '5000:5000'
        deploy:
          placement:
            constraints:
              - node.labels.short_name == swarm-0
EOF
docker stack rm beamup_control
docker stack deploy --compose-file registry.yaml beamup_control

sleep 60

beamup-sync-swarm apps.yaml apps.conf
APPS_COUNT=`cat apps.yaml | grep image | wc -l`
if [ $APPS_COUNT -gt 0 ] ; then
	docker stack deploy --prune --compose-file apps.yaml beamup
fi
