#!/usr/bin/env bash


# Or actually, alternatively we can do
# docker service create --name beamup_control_registry --mount type=volume,source=/var/lib/registry,destination=/var/lib/registry --publish published=5000,target=5000 registry:2

mkdir -p /var/lib/registry
cat <<EOF >registry.yaml
version: '3.7'
services:
   registry:
        image: registry:2
        volumes:
          - /var/lib/registry:/var/lib/registry
        ports:
          - '5000:5000'
   nginx-proxy:
        image: jwilder/nginx-proxy
        deploy:
          mode: 'global'
        ports:
          - target: 80
            published: 80
            # ensure nginx does not pass through ingress routing
            mode: host
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
EOF
docker stack deploy --compose-file registry.yaml beamup_control

# @TODO better name
beamup-sync-swarm > apps.yaml
docker stack deploy --prune --compose-file apps.yaml beamup 
