- hosts: deployer
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Update nodejs package apt /modern version/
      shell: 'curl -sL https://deb.nodesource.com/setup_20.x | bash - '

    - name: Install nodejs
      apt:
        name: nodejs
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: file | Configure appropiate symbolic links for nodejs
      file:
        src: "{{ item.source }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - { source: "/usr/bin/node", dest: "/etc/alternatives/nodejs" }
        - { source: "/etc/alternatives/nodejs", dest: "/usr/bin/nodejs" }

    - name: Install vim
      apt:
        name: vim
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Install jq
      apt:
        name: jq
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: apt | Install rsync
      apt:
        name: rsync
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: apt | Install logrotate
      ansible.builtin.apt:
        name: logrotate
        state: present
        update_cache: yes
        cache_valid_time: 3600

     # Install sysstat for sar reporting
    - name: Install sysstat
      apt:
        name: sysstat
        state: present

    - name: Configure sysstat
      lineinfile:
        dest: /etc/default/sysstat
        regexp: '^ENABLED='
        line: 'ENABLED="true"'
        state: present

    - name: Start sysstat
      service:
        name: sysstat
        state: started
        enabled: yes
