- hosts: swarm
  tasks:
    - name: Disable IPv6 [1/2]
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6 
        value: 1
        state: present

    - name: Disable IPv6 [2/2]
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: 1
        state: present

    - name: Disable swapinness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: 0
        state: present

    - name: Disable overcommit memory
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: 1
        state: present
        reload: yes
