#!/usr/bin/env bash

set -e

###
# Commands
###

case "$1" in
        logs)
                docker service logs -n 100 -t --no-task-ids --no-resolve beamup_"$2" | awk '{$2=""; print $0}'
                ;;
        sync)
                /home/beamup/beamup-sync-swarm.sh
                ;;
        sync-config)
                beamup-store-app-config "$2"
                /home/beamup/beamup-sync-swarm.sh
                ;;
        delete-config)
                if [[ ! "$2" =~ ^[a-z0-9-]+$ ]]; then
                        echo "Invalid app name" >&2
                        exit 1
                fi
                rm -f "/home/beamup/.beamup-app-config/$2.json"
                ;;
        swarm-nodes)
                docker node ls
                ;;
        server-stats)
                server-stats
                ;;
        projects)
                docker service ls
                ;;
        project-logs)
                docker service logs --raw -t beamup_"$2"
                ;;
        project-update)
                docker service update --force beamup_"$2"
                ;;
        *)
                echo "Invalid command"
                exit 1
                ;;
esac
