#!/usr/bin/env bash

set -e

###
# Commands
###


if [ "$1" = "logs" ];
then
        docker service logs -n 100 -t --no-task-ids --no-resolve beamup_"$2" | awk '{$2=""; print $0}'
        exit 0
fi

if [ "$1" = "sync" ]
then
        /home/beamup/beamup-sync-swarm.sh
        exit 0
fi
