#!/usr/bin/env bash

set -e

###
# Commands
###

# if we don't do this, dokku just executes that...
unset SSH_ORIGINAL_COMMAND

if [ "$1" = "sync-github-keys" ];
then
	beamup-sync-keys "$HOME/.ssh/authorized_keys" "$2" && echo "Successfully authorized GitHub user $2"
	exit 0
fi

GITHUB_USER=`echo $GITHUB_USER | awk '{print tolower($0)}'`
if [ -z "$GITHUB_USER" ]
then
	echo "No GITHUB_USER: unauthorized"
	exit 1
fi

if [ "$1" = "git-receive-pack" ] || [ "$1" = "config:set" ] || [ "$1" = "config:get" ] || [ "$1" = "logs" ];
then
	# NOTE: this is safe because GitHub usernames cannot have `-` in them
	APP_NAME="$(echo "$2" | tr '/' '-' | tr -d '"' | tr -d \')"
	VALIDATION_PATTERN="^[a-zA-Z0-9-]*$"
	GITHUB_USER_HASHED=$( echo $GITHUB_USER | shasum -a 256 | cut -c1-12 )
	if [[ ! $APP_NAME =~ $VALIDATION_PATTERN ]]; then
		echo "app name is invalid: please note that the only alphanumeric characters and '-' are supported"
		exit 1
	fi
	if [[ ! -d $APP_NAME ]] && [[ `echo "$GITHUB_USER_HASHED"-* | wc -w` -gt 20 ]]
	then
		echo "addons per user limit reached"
		exit 1
	fi
	case "$APP_NAME" in
		${GITHUB_USER_HASHED}-*) dokku $1 $APP_NAME "$3";;
		*)  exit 1 ;;
	esac
else
	echo "unsupported command"
	exit 1
fi
