#!/bin/sh

set -e

###
# Functions
###


###
# Commands
###
if [ "$1" = "sync-github-keys" ];
then
	beamup-sync-keys "$HOME/.ssh/authorized_keys" "$2"
	exit 0
fi

if [ -z "$GITHUB_USER" ]
then
	echo "No GITHUB_USER: unauthorized"
	exit 1
fi

echo $GITHUB_USER

